### PR TITLE
feat(camera_info,tf): use camera info and TF instead of config file

### PR DESCRIPTION
**Pull request by Owen-Liuyuxuan**
## Description

Using camera info and tf computed from the ROS2 system.

https://github.com/user-attachments/assets/78277126-5df7-4af2-bd13-a36c14be80d9

I tested the codes with 

https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge

It works well with the TF tree and standard camera info as specified in that repo.

## Related links

**Parent Issue:**
- https://github.com/autowarefoundation/autoware.universe/pull/7956

## Notes for reviewers

None.

## Interface changes

Subscribing to Camera info Topics and TF trees now.

Not reading the cam_params.yaml

## Effects on system behavior

None.

### CODE REVIEW

**Comment by Owen-Liuyuxuan** [comment]
@cyn-liu The last error in spell check CI is on the word "voxelization" which should be added to the dictionary instead of dealing in codes.

**Comment by cyn-liu** [comment]
@Owen-Liuyuxuan Thanks your contribution, great job!

I clone your PR, and want run it on mine environment. When I want get ros2 topics of nuscenes dataset , I meet some problem,
I cannot run [ros2_dataset_bridge](https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge) correctly. could you give me some advice?
```bash
# ros2 launch ros2_dataset_bridge nuscenes_launch.xml 
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-08-26-09-04-13-164291-ros-5829
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [nuscenes_visualize_node-1]: process started with pid [5830]
[INFO] [rviz2-2]: process started with pid [5832]
[INFO] [gui_controller-3]: process started with pid [5834]
[rviz2-2] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[gui_controller-3] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[nuscenes_visualize_node-1] /usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 2.1.0
[nuscenes_visualize_node-1]   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[nuscenes_visualize_node-1] Traceback (most recent call last):
[nuscenes_visualize_node-1]   File "/home/ros/new-workspace/ws_lc/autoware_ws/ros2_dataset/install/ros2_dataset_bridge/lib/ros2_dataset_bridge/nuscenes_visualize_node", line 33, in <module>
[nuscenes_visualize_node-1]     sys.exit(load_entry_point('ros2-dataset-bridge', 'console_scripts', 'nuscenes_visualize_node')())
[nuscenes_visualize_node-1]   File "/home/ros/new-workspace/ws_lc/autoware_ws/ros2_dataset/install/ros2_dataset_bridge/lib/ros2_dataset_bridge/nuscenes_visualize_node", line 25, in importlib_load_entry_point
[nuscenes_visualize_node-1]     return next(matches).load()
[nuscenes_visualize_node-1]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[nuscenes_visualize_node-1]     module = import_module(match.group('module'))
[nuscenes_visualize_node-1]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[nuscenes_visualize_node-1]     return _bootstrap._gcd_import(name[level:], package, level)
[nuscenes_visualize_node-1]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[nuscenes_visualize_node-1]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[nuscenes_visualize_node-1]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[nuscenes_visualize_node-1]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[nuscenes_visualize_node-1]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[nuscenes_visualize_node-1]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[nuscenes_visualize_node-1]   File "/home/ros/new-workspace/ws_lc/autoware_ws/ros2_dataset/build/ros2_dataset_bridge/ros2_dataset_bridge/nuscenes_visualize_node.py", line 8, in <module>
[nuscenes_visualize_node-1]     from .utils.ros_util import ROSInterface
[nuscenes_visualize_node-1]   File "/home/ros/new-workspace/ws_lc/autoware_ws/ros2_dataset/build/ros2_dataset_bridge/ros2_dataset_bridge/utils/ros_util.py", line 22, in <module>
[nuscenes_visualize_node-1]     from scipy.spatial.transform import Rotation as R
[nuscenes_visualize_node-1]   File "/usr/lib/python3/dist-packages/scipy/spatial/__init__.py", line 102, in <module>
[nuscenes_visualize_node-1]     from ._kdtree import *
[nuscenes_visualize_node-1]   File "/usr/lib/python3/dist-packages/scipy/spatial/_kdtree.py", line 5, in <module>
[nuscenes_visualize_node-1]     from ._ckdtree import cKDTree, cKDTreeNode
[nuscenes_visualize_node-1]   File "_ckdtree.pyx", line 1, in init scipy.spatial._ckdtree
[nuscenes_visualize_node-1] ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
[ERROR] [nuscenes_visualize_node-1]: process has died [pid 5830, exit code 1, cmd '/home/ros/new-workspace/ws_lc/autoware_ws/ros2_dataset/install/ros2_dataset_bridge/lib/ros2_dataset_bridge/nuscenes_visualize_node --ros-args -r __node:=nuscenes_visualize_node --params-file /tmp/launch_params_ko6j667m --params-file /tmp/launch_params_7mb14_7b --params-file /tmp/launch_params_p1kchsg9'].
[rviz2-2] [INFO] [1724663053.552407221] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724663053.552501677] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-2] [INFO] [1724663053.646021722] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724663053.718782449] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724663053.723574684] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724663053.728359898] [rviz2]: Stereo is NOT SUPPORTED
``` 
my `nuscenes_launch.xml`:
```
<?xml version="1.0"?>
<launch>
    <arg name="NUSCENES_DIR" default="/my_dataset_absolute_path/nuscene_mini"/>
    <arg name="NUSCENES_VER" default="v1.0-mini"/>
    <arg name="UPDATE_FREQUENCY" default="4.0"/>

    <node pkg="ros2_dataset_bridge" exec="nuscenes_visualize_node" name="nuscenes_visualize_node" output="screen">
        <param name="NUSCENES_DIR" value="$(var NUSCENES_DIR)"/>
        <param name="NUSCENES_VER" value="$(var NUSCENES_VER)"/>
        <param name="UPDATE_FREQUENCY" value="$(var UPDATE_FREQUENCY)"/>
    </node>
    <node pkg="rviz2" exec="rviz2" name="rviz2" args="-d $(find-pkg-share ros2_dataset_bridge)/rviz/nuscenes.rviz"/>
    <node pkg="ros2_dataset_bridge" exec="gui_controller" name="GUI_controller_node" output="screen" respawn="false" respawn_delay="0">

    </node>
</launch>
```

**Comment by Owen-Liuyuxuan** [comment]
That is related to numpy version and scipy version.

You can try `from scipy.spatial.transform import Rotation as R` and make sure it has an error or not.

I am using (I guess quite many versions work)

```yaml
python: 3.10
numpy: 1.26.4
scipy: 1.8.0
```

And try to re-install them if necessary?

**Comment by cyn-liu** [comment]
@Owen-Liuyuxuan  The version problem has been resolved and the node can running, but why the node been stuck in this position, without pub data. 
```bash
# ros2 launch ros2_dataset_bridge nuscenes_launch.xml 
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-08-27-09-48-29-878998-ros-7440
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [nuscenes_visualize_node-1]: process started with pid [7441]
[INFO] [rviz2-2]: process started with pid [7443]
[INFO] [gui_controller-3]: process started with pid [7445]
[rviz2-2] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[gui_controller-3] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[nuscenes_visualize_node-1] /usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
[nuscenes_visualize_node-1]   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[rviz2-2] [INFO] [1724752110.222268196] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724752110.222375737] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-2] [INFO] [1724752110.255763206] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724752110.437645916] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724752110.445807604] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1724752110.452218968] [rviz2]: Stereo is NOT SUPPORTED
[nuscenes_visualize_node-1] [INFO] [1724752110.855540910] [nuscenes_visualize_node]: Waiting for nuscenes to load
[nuscenes_visualize_node-1] [INFO] [1724752111.357436555] [nuscenes_visualize_node]: nuscenes loaded
```
```bash
# ros2 node list
/GUI_controller_node
/nuscenes_visualize_node
/rviz2
/transform_listener_impl_562251108f70
```

```bash
# ros2 topic info -v /nuscenes/CAM_FRONT/image
Type: sensor_msgs/msg/Image

Publisher count: 0

Subscription count: 1

Node name: rviz2
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: SUBSCRIPTION
GID: 01.10.5d.b7.56.20.9b.f1.1d.77.7a.c2.00.00.2b.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (5)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite
```
If I want to obtain the topic of nuscenes dataset, what other operations do I need besides running this launch file? there is no problem with the path of my nuscenes mini data.

**Comment by Owen-Liuyuxuan** [comment]
@cyn-liu 
I guess you can raise an issue on my repo...

After seeing the "nuscenes loaded" logging, go to the QT UI board to control the flowing of the data. As shown in the demo video in my readme.

https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge/blob/main/docs/nusc_readme.md

https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge/tree/main?tab=readme-ov-file#gui

**Comment by cyn-liu** [comment]
>  I guess you can raise an issue on my repo...
> 
> After seeing the "nuscenes loaded" logging, go to the QT UI board to control the flowing of the data. As shown in the demo video in my readme.
> 
> https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge/blob/main/docs/nusc_readme.md
> 
> https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge/tree/main?tab=readme-ov-file#gui

@Owen-Liuyuxuan Thanks for your patient reply. I already resolve this problem. when seeing the "nuscenes loaded" logging, I must click `stop` checkbox  to cancel the `√`  in GUI.

**Comment by cyn-liu** [comment]
@Owen-Liuyuxuan  [ros2_dataset_bridge](https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge) repo and this PR are both great jobs. `ros2_dataset_bridge` make our test more convenient, and this PR makes my PR more standardized. These are very worth learning from. Thank you

**Pull request merged**
